### ISSUE TITLE
[Math-for-programmers] Epsilon and \in ("element") are not the same

### ISSUE THREAD

**Issue by vatai** [amitness/amitness.github.io#53]
In you lovely post about math and programming you say that the python `in` is the same as the "epsilon". I'd argue that this is not true. ϵ and ∈are two different symbols. ϵ is the Greek letter epsilon (like alpha or beta), and is used for infinitesimally small quantities or as the "error" term, while the ∈"element of", "in" symbol is what you are describing and has nothing to do with the letter epsilon. See 5th paragraph at [here](https://en.wikipedia.org/wiki/Epsilon) which read "The lunate epsilon (ϵ) is not to be confused with the set membership symbol (∈);"

Best,
Emil

**Comment by amitness** [comment]
@vatai Thank you so much for the correction. I'll update the post.

**Comment by amitness** [comment]
Post updated. Closing this and thanks for clarifying this @vatai
