### ISSUE TITLE
Mistake in citation

### ISSUE THREAD

**Issue by NLP-cr** [amitness/amitness.github.io#55]
Thank you for the review.

Please note that the Generative Methods technic you presented (8) was first proposed by the paper:
Not Enough Data? Deep Learning to the Rescue! (https://arxiv.org/abs/1911.03118) .

It also appeared at VentureBeat and published in the AAAI19 conference.
https://venturebeat.com/2019/11/14/ibms-lambada-ai-generates-training-data-for-text-classifiers/

I think you should give the credit to the IBM team...

**Comment by amitness** [comment]
Hi,

Sure, I will review the links and do the corrections.

**Comment by amitness** [comment]
I've added the corrections.
