### ISSUE TITLE
POST /api/v1/download HTTP/1.1" 422 Unprocessable Entity i am getting this error while post data to fastapi

### ISSUE THREAD

**Issue by palani4194** [amitness/amitness.github.io#56]
@router.post('/download')
def download(json_data: Dict):
    url = json_data.get('url')
    return url

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type=text/javascript>
            $(function() {
              $('a#download').bind('click', function() {
                var url = $("#url").val();
                var data = {'url': url}
                 $.ajax({
                    url: '/api/v1/download',
                    type: 'post',
                    data : data,
                    contentType: 'application/json',
                    success: function (data) {
                      console.log(data);

                    },
                });
              });
            });
    </script>

**Comment by palani4194** [comment]
please let me know how to send data from ajax to fastapi and return in fast api response?

**Comment by amitness** [comment]
Hey sorry. I missed your issue. Have you solved it already?
