### ISSUE TITLE
Create Annotations with Self-Supervised Learning

### ISSUE THREAD

**Issue by timothyvanco** [amitness/amitness.github.io#60]
My task is to use self-supervised learning (SSL) to find features - labels from pictures (dataset consist of similar pictures with small differences) and then self label it - create annotations. For example take CIFAR10 dataset, use few labels to teach a model and then, show where on the testing picture is one of the class/label of CIFAR10 dataset. For example, teach to recognise cars with 10 label pictures and then show picture with car and model will be able to create annotation = mask, where is the car on the picture.

So I want to ask, which method from SSL should I use (SimCLR, MoCo, or other?) and what is more important, how to create annotations and/or self labels?

thanks for your time :)

**Comment by amitness** [comment]
@timothyvanco None of them would work. These methods are meant for pre-training and can't be used as you suggested.

You can't train a classification model and expect it to segment/mask the region for object detection.

I'm not entirely sure what your use case is, but look into the below links. The first one uses `semi-supervised` learning for object detection.
- https://towardsdatascience.com/from-research-to-production-with-deep-semi-supervised-learning-7caaedc39093

Another related paper is self-labeling that auto-clusters similar images together.
- https://amitness.com/2020/04/illustrated-self-labelling/

**Comment by timothyvanco** [comment]
hi, thanks for respond. I understand more now. So my task is to do instance segmentation. Is it possible to do it with SSL? I know for example, that CNNs like R-CNN, Fast/Faster R-CNN or Mask R-CNN are used on this but is it possible to use these CNNs with some pretext task from SSL? Because I want to do instance segmentation as you said but I wont have enough data - so I need to use SSL methods to solve this, or?
