### ISSUE TITLE
The password isn't useful,why?

### ISSUE THREAD

**Issue by 01build** [amitness/amitness.github.io#61]

**Comment by amitness** [comment]
What do you mean?

**Comment by 01build** [comment]
![QQ截图20201117113427](https://user-images.githubusercontent.com/59005451/99343454-e70ea900-28c8-11eb-9fcb-bf17be72252d.png)
here，the password I have tried many times，but the web said it is incorrect

**Comment by amitness** [comment]
@01build Yes, looks like there is an issue on the library end. Please open an issue at 

https://github.com/abhishekkrthakur/colabcode

In the meantime, you can use it without setting any password.
```
from colabcode import ColabCode

ColabCode(port=8000)
```
